### ISSUE TITLE
UWP scale problem

### ISSUE THREAD

**Issue by gaetandezeiraud** [dmanning23/ResolutionBuddy#2]
Hello,
First thank you for your work. I have a small problem with the use of your UWP code (Creators Update).
The changes on the viewport are good for the height and width, but there is not scale the content (for width resize). It remains unchanged.

But, this is good when the application start, but not after window resize. Here's a video: https://youtu.be/1iSYhadDiEA.

Do you have an idea of why? My code is almost identical to your UWP Windows 10 example.
Thank you !

**Comment by dmanning23** [comment]
I think it is a bug in my code...

https://github.com/dmanning23/ResolutionBuddy/blob/master/Source/Resolution.cs#L218

If width is less than height, it is doing some funny stuff.  I will look into it and see if I can fix.
Cheers!

**Comment by gaetandezeiraud** [comment]
Hi,
Thank you for your response and your responsiveness!
If you get to correct it actually thank you. :)

Best Regards.

**Comment by dmanning23** [comment]
This was fixed in the commit:
https://github.com/dmanning23/ResolutionBuddy/commit/acad2c17434737cbfe317f8ccdb5f4964e917e24#diff-105ebc09b284ba3b3cca1b4a65a788fc

The latest nuget package will also contain this fix.
Cheers!
